services:
  diaz_app:
    container_name: diaz_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - diaz_mongo
    environment:
      - MONGODB_URI=mongodb://diaz_mongo:27017/database
      - JWT_SECRET=supersecretkey12345!@
    links:
      - diaz_mongo
  diaz_mongo:
    container_name: diaz_mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
