services:
  app:
    container_name: diaz_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    links:
      - "mongo:mongosrv"
  mongo:
    container_name: diaz_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"